<?php
/**
 * -- file description --
 *
 * @author Marko Krüger <plant2code@marko-krueger.de>
 *
 */

namespace Tests;


use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Tymon\JWTAuth\Facades\JWTAuth;


/**
 * Class TestResource
 *
 * @package Tests
 */
class TestResource extends TestCase
{
    /**
     * @var
     */
    public $token;

    public $user;

    /**
     * @param array $data
     */
    public function login($data = ['username' => 'holla_die_waldfee', 'password' => '1234'])
    {
        $response = $this->post('api/authenticate', $data);
        $content = json_decode($response->getContent());

        $this->token = $content->token;
    }


    /**
     *
     */
    public function setUp()
    {
        parent::setUp();

        $user = new User(
            [
                'username' => 'holla_die_waldfee',
                'password' => Hash::make('1234'),
                'fullname' => 'Holla die Waldfee',
                'email'    => 'holla@localhost'
            ]
        );
        $user->save();
        $this->user = $user;
        $this->be($user);
        $this->token = JWTAuth::fromUser($user);
    }

    /**
     * @param string $method
     * @param string $uri
     * @param array  $data
     * @param array  $headers
     *
     * @return \Illuminate\Foundation\Testing\TestResponse
     */
    public function json($method, $uri, array $data = [], array $headers = [])
    {
        $headers = [
            'Authorization' => 'Bearer ' . $this->token
        ];

        return parent::json($method, $uri, $data, $headers); // TODO: Change the autogenerated stub
    }


    /**
     *
     */
    public function testIndex()
    {
        $this->markTestIncomplete('Test is not implemented.');
    }

    /**
     *
     */
    public function testRead()
    {
        $this->markTestIncomplete('Test is not implemented.');
    }

    /**
     *
     */
    public function testCreate()
    {
        $this->markTestIncomplete('Test is not implemented.');
    }

    /**
     *
     */
    public function testUpdate()
    {
        $this->markTestIncomplete('Test is not implemented.');
    }


}
