<?php

namespace App\JsonApi\Users;


use App\Models\User;
use CloudCreativity\LaravelJsonApi\Schema\EloquentSchema;

class Schema extends EloquentSchema
{

    /**
     * @var string
     */
    protected $resourceType = 'users';

    /**
     * @var array|null
     */
    protected $attributes = ['username', 'fullname', 'email'];

    /**
     * @param User  $resource
     * @param bool  $isPrimary
     * @param array $includeRelationships
     *
     * @return array
     */
    public function getRelationships($resource, $isPrimary, array $includeRelationships)
    {
        return parent::getRelationships($resource, $isPrimary, $includeRelationships); // TODO: Change the autogenerated stub
    }


}

